# Generated by Django 2.2.1 on 2019-05-13 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='midwife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
